#!/usr/bin/env python3
"""Capture Khronos' own DFD for every VkFormat ktx2-fetch writes.

For each format: `ktx create --raw` an 8x8 file, `ktx validate` it, and
record (a) the DFD bytes to tests/fixtures/dfd/<NAME>.dfd, (b) the header's
vkFormat and typeSize to tests/fixtures/dfd/index.tsv, (c) an include_bytes!
table to src/dfd_ref.rs. Re-run whenever a row is added to vkformat.rs.
Requires `ktx` (v5.0.0-rc1 or later) on PATH.
"""
import math, pathlib, struct, subprocess, sys, tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
FIX = ROOT / "tests" / "fixtures" / "dfd"
FIX.mkdir(parents=True, exist_ok=True)

def U(n, bpp): return (n, bpp, None)
def C(n, bw, bh, bb): return (n, None, (bw, bh, bb))

FORMATS = [
    U("A8_UNORM_KHR", 1),
    U("R8_UNORM", 1), U("R8_SRGB", 1), U("R8_SNORM", 1), U("R8_UINT", 1), U("R8_SINT", 1),
    U("R8G8_UNORM", 2), U("R8G8_SRGB", 2), U("R8G8_SNORM", 2), U("R8G8_UINT", 2), U("R8G8_SINT", 2),
    U("R8G8B8A8_UNORM", 4), U("R8G8B8A8_SRGB", 4), U("R8G8B8A8_SNORM", 4), U("R8G8B8A8_UINT", 4), U("R8G8B8A8_SINT", 4),
    U("B8G8R8A8_UNORM", 4), U("B8G8R8A8_SRGB", 4),
    U("R16_UNORM", 2), U("R16_SNORM", 2), U("R16_UINT", 2), U("R16_SINT", 2), U("R16_SFLOAT", 2),
    U("R16G16_UNORM", 4), U("R16G16_SNORM", 4), U("R16G16_UINT", 4), U("R16G16_SINT", 4), U("R16G16_SFLOAT", 4),
    U("R16G16B16A16_UNORM", 8), U("R16G16B16A16_SNORM", 8), U("R16G16B16A16_UINT", 8), U("R16G16B16A16_SINT", 8), U("R16G16B16A16_SFLOAT", 8),
    U("R32_UINT", 4), U("R32_SINT", 4), U("R32_SFLOAT", 4),
    U("R32G32_UINT", 8), U("R32G32_SINT", 8), U("R32G32_SFLOAT", 8),
    U("R32G32B32A32_UINT", 16), U("R32G32B32A32_SINT", 16), U("R32G32B32A32_SFLOAT", 16),
    U("D16_UNORM", 2), U("D32_SFLOAT", 4), U("S8_UINT", 1),
    C("BC1_RGBA_UNORM_BLOCK", 4, 4, 8), C("BC1_RGBA_SRGB_BLOCK", 4, 4, 8),
    C("BC2_UNORM_BLOCK", 4, 4, 16), C("BC2_SRGB_BLOCK", 4, 4, 16),
    C("BC3_UNORM_BLOCK", 4, 4, 16), C("BC3_SRGB_BLOCK", 4, 4, 16),
    C("BC4_UNORM_BLOCK", 4, 4, 8), C("BC4_SNORM_BLOCK", 4, 4, 8),
    C("BC5_UNORM_BLOCK", 4, 4, 16), C("BC5_SNORM_BLOCK", 4, 4, 16),
    C("BC6H_SFLOAT_BLOCK", 4, 4, 16), C("BC6H_UFLOAT_BLOCK", 4, 4, 16),
    C("BC7_UNORM_BLOCK", 4, 4, 16), C("BC7_SRGB_BLOCK", 4, 4, 16),
    C("ETC2_R8G8B8_UNORM_BLOCK", 4, 4, 8), C("ETC2_R8G8B8_SRGB_BLOCK", 4, 4, 8),
    C("ETC2_R8G8B8A1_UNORM_BLOCK", 4, 4, 8), C("ETC2_R8G8B8A1_SRGB_BLOCK", 4, 4, 8),
    C("ETC2_R8G8B8A8_UNORM_BLOCK", 4, 4, 16), C("ETC2_R8G8B8A8_SRGB_BLOCK", 4, 4, 16),
    C("EAC_R11_UNORM_BLOCK", 4, 4, 8), C("EAC_R11_SNORM_BLOCK", 4, 4, 8),
    C("EAC_R11G11_UNORM_BLOCK", 4, 4, 16), C("EAC_R11G11_SNORM_BLOCK", 4, 4, 16),
]
for bw, bh in [(4, 4), (5, 4), (5, 5), (6, 5), (6, 6), (8, 5), (8, 6), (8, 8),
               (10, 5), (10, 6), (10, 8), (10, 10), (12, 10), (12, 12)]:
    for suffix in ["UNORM", "SRGB", "SFLOAT"]:
        FORMATS.append(C(f"ASTC_{bw}x{bh}_{suffix}_BLOCK", bw, bh, 16))

W = H = 8
index_lines = []
ref_arms = []
with tempfile.TemporaryDirectory() as tmp:
    tmp = pathlib.Path(tmp)
    for name, bpp, blk in FORMATS:
        if bpp:
            n = W * H * bpp
        else:
            bw, bh, bb = blk
            n = math.ceil(W / bw) * math.ceil(H / bh) * bb
        raw = tmp / f"{name}.raw"
        raw.write_bytes((bytes(range(256)) * (n // 256 + 1))[:n])
        out = tmp / f"{name}.ktx2"
        subprocess.run(["ktx", "create", "--raw", "--format", name, "--width", str(W),
                        "--height", str(H), str(raw), str(out)], check=True)
        subprocess.run(["ktx", "validate", str(out)], check=True)
        b = out.read_bytes()
        vk_format, type_size = struct.unpack_from("<II", b, 12)
        dfd_off, dfd_len = struct.unpack_from("<II", b, 48)
        (FIX / f"{name}.dfd").write_bytes(b[dfd_off:dfd_off + dfd_len])
        index_lines.append(f"{name}\t{vk_format}\t{type_size}")
        ref_arms.append(f'        "{name}" => Some(include_bytes!("../tests/fixtures/dfd/{name}.dfd")),')

(FIX / "index.tsv").write_text("\n".join(index_lines) + "\n")
(ROOT / "src" / "dfd_ref.rs").write_text(
    "//! GENERATED by tools/capture-dfd-fixtures.py. Do not edit.\n"
    "//!\n"
    "//! Khronos' own Data Format Descriptor for each VkFormat this tool writes,\n"
    "//! as emitted by `ktx create --raw` (v5.0.0-rc1) for an 8x8 image. The DFD\n"
    "//! does not depend on image size. `primaries` is left as Khronos wrote it\n"
    "//! (BT709 for colour); `dfd::build` overrides it to UNSPECIFIED.\n\n"
    "/// The reference DFD bytes for `name` (a VkFormat name without the\n"
    "/// `VK_FORMAT_` prefix), or `None` if no fixture was captured for it.\n"
    "pub fn reference(name: &str) -> Option<&'static [u8]> {\n"
    "    match name {\n" + "\n".join(ref_arms) + "\n        _ => None,\n    }\n}\n")
print(f"captured {len(FORMATS)} formats", file=sys.stderr)
