//! GENERATED by tools/capture-dfd-fixtures.py. Do not edit.
//!
//! Khronos' own Data Format Descriptor for each VkFormat this tool writes,
//! as emitted by `ktx create --raw` (v5.0.0-rc1) for an 8x8 image. The DFD
//! does not depend on image size. `primaries` is left as Khronos wrote it
//! (BT709 for colour); `dfd::build` overrides it to UNSPECIFIED.

/// The reference DFD bytes for `name` (a VkFormat name without the
/// `VK_FORMAT_` prefix), or `None` if no fixture was captured for it.
pub fn reference(name: &str) -> Option<&'static [u8]> {
    match name {
        "A8_UNORM_KHR" => Some(include_bytes!("../tests/fixtures/dfd/A8_UNORM_KHR.dfd")),
        "R8_UNORM" => Some(include_bytes!("../tests/fixtures/dfd/R8_UNORM.dfd")),
        "R8_SRGB" => Some(include_bytes!("../tests/fixtures/dfd/R8_SRGB.dfd")),
        "R8_SNORM" => Some(include_bytes!("../tests/fixtures/dfd/R8_SNORM.dfd")),
        "R8_UINT" => Some(include_bytes!("../tests/fixtures/dfd/R8_UINT.dfd")),
        "R8_SINT" => Some(include_bytes!("../tests/fixtures/dfd/R8_SINT.dfd")),
        "R8G8_UNORM" => Some(include_bytes!("../tests/fixtures/dfd/R8G8_UNORM.dfd")),
        "R8G8_SRGB" => Some(include_bytes!("../tests/fixtures/dfd/R8G8_SRGB.dfd")),
        "R8G8_SNORM" => Some(include_bytes!("../tests/fixtures/dfd/R8G8_SNORM.dfd")),
        "R8G8_UINT" => Some(include_bytes!("../tests/fixtures/dfd/R8G8_UINT.dfd")),
        "R8G8_SINT" => Some(include_bytes!("../tests/fixtures/dfd/R8G8_SINT.dfd")),
        "R8G8B8A8_UNORM" => Some(include_bytes!("../tests/fixtures/dfd/R8G8B8A8_UNORM.dfd")),
        "R8G8B8A8_SRGB" => Some(include_bytes!("../tests/fixtures/dfd/R8G8B8A8_SRGB.dfd")),
        "R8G8B8A8_SNORM" => Some(include_bytes!("../tests/fixtures/dfd/R8G8B8A8_SNORM.dfd")),
        "R8G8B8A8_UINT" => Some(include_bytes!("../tests/fixtures/dfd/R8G8B8A8_UINT.dfd")),
        "R8G8B8A8_SINT" => Some(include_bytes!("../tests/fixtures/dfd/R8G8B8A8_SINT.dfd")),
        "B8G8R8A8_UNORM" => Some(include_bytes!("../tests/fixtures/dfd/B8G8R8A8_UNORM.dfd")),
        "B8G8R8A8_SRGB" => Some(include_bytes!("../tests/fixtures/dfd/B8G8R8A8_SRGB.dfd")),
        "R16_UNORM" => Some(include_bytes!("../tests/fixtures/dfd/R16_UNORM.dfd")),
        "R16_SNORM" => Some(include_bytes!("../tests/fixtures/dfd/R16_SNORM.dfd")),
        "R16_UINT" => Some(include_bytes!("../tests/fixtures/dfd/R16_UINT.dfd")),
        "R16_SINT" => Some(include_bytes!("../tests/fixtures/dfd/R16_SINT.dfd")),
        "R16_SFLOAT" => Some(include_bytes!("../tests/fixtures/dfd/R16_SFLOAT.dfd")),
        "R16G16_UNORM" => Some(include_bytes!("../tests/fixtures/dfd/R16G16_UNORM.dfd")),
        "R16G16_SNORM" => Some(include_bytes!("../tests/fixtures/dfd/R16G16_SNORM.dfd")),
        "R16G16_UINT" => Some(include_bytes!("../tests/fixtures/dfd/R16G16_UINT.dfd")),
        "R16G16_SINT" => Some(include_bytes!("../tests/fixtures/dfd/R16G16_SINT.dfd")),
        "R16G16_SFLOAT" => Some(include_bytes!("../tests/fixtures/dfd/R16G16_SFLOAT.dfd")),
        "R16G16B16A16_UNORM" => Some(include_bytes!(
            "../tests/fixtures/dfd/R16G16B16A16_UNORM.dfd"
        )),
        "R16G16B16A16_SNORM" => Some(include_bytes!(
            "../tests/fixtures/dfd/R16G16B16A16_SNORM.dfd"
        )),
        "R16G16B16A16_UINT" => Some(include_bytes!(
            "../tests/fixtures/dfd/R16G16B16A16_UINT.dfd"
        )),
        "R16G16B16A16_SINT" => Some(include_bytes!(
            "../tests/fixtures/dfd/R16G16B16A16_SINT.dfd"
        )),
        "R16G16B16A16_SFLOAT" => Some(include_bytes!(
            "../tests/fixtures/dfd/R16G16B16A16_SFLOAT.dfd"
        )),
        "R32_UINT" => Some(include_bytes!("../tests/fixtures/dfd/R32_UINT.dfd")),
        "R32_SINT" => Some(include_bytes!("../tests/fixtures/dfd/R32_SINT.dfd")),
        "R32_SFLOAT" => Some(include_bytes!("../tests/fixtures/dfd/R32_SFLOAT.dfd")),
        "R32G32_UINT" => Some(include_bytes!("../tests/fixtures/dfd/R32G32_UINT.dfd")),
        "R32G32_SINT" => Some(include_bytes!("../tests/fixtures/dfd/R32G32_SINT.dfd")),
        "R32G32_SFLOAT" => Some(include_bytes!("../tests/fixtures/dfd/R32G32_SFLOAT.dfd")),
        "R32G32B32A32_UINT" => Some(include_bytes!(
            "../tests/fixtures/dfd/R32G32B32A32_UINT.dfd"
        )),
        "R32G32B32A32_SINT" => Some(include_bytes!(
            "../tests/fixtures/dfd/R32G32B32A32_SINT.dfd"
        )),
        "R32G32B32A32_SFLOAT" => Some(include_bytes!(
            "../tests/fixtures/dfd/R32G32B32A32_SFLOAT.dfd"
        )),
        "D16_UNORM" => Some(include_bytes!("../tests/fixtures/dfd/D16_UNORM.dfd")),
        "D32_SFLOAT" => Some(include_bytes!("../tests/fixtures/dfd/D32_SFLOAT.dfd")),
        "S8_UINT" => Some(include_bytes!("../tests/fixtures/dfd/S8_UINT.dfd")),
        "BC1_RGBA_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/BC1_RGBA_UNORM_BLOCK.dfd"
        )),
        "BC1_RGBA_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/BC1_RGBA_SRGB_BLOCK.dfd"
        )),
        "BC2_UNORM_BLOCK" => Some(include_bytes!("../tests/fixtures/dfd/BC2_UNORM_BLOCK.dfd")),
        "BC2_SRGB_BLOCK" => Some(include_bytes!("../tests/fixtures/dfd/BC2_SRGB_BLOCK.dfd")),
        "BC3_UNORM_BLOCK" => Some(include_bytes!("../tests/fixtures/dfd/BC3_UNORM_BLOCK.dfd")),
        "BC3_SRGB_BLOCK" => Some(include_bytes!("../tests/fixtures/dfd/BC3_SRGB_BLOCK.dfd")),
        "BC4_UNORM_BLOCK" => Some(include_bytes!("../tests/fixtures/dfd/BC4_UNORM_BLOCK.dfd")),
        "BC4_SNORM_BLOCK" => Some(include_bytes!("../tests/fixtures/dfd/BC4_SNORM_BLOCK.dfd")),
        "BC5_UNORM_BLOCK" => Some(include_bytes!("../tests/fixtures/dfd/BC5_UNORM_BLOCK.dfd")),
        "BC5_SNORM_BLOCK" => Some(include_bytes!("../tests/fixtures/dfd/BC5_SNORM_BLOCK.dfd")),
        "BC6H_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/BC6H_SFLOAT_BLOCK.dfd"
        )),
        "BC6H_UFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/BC6H_UFLOAT_BLOCK.dfd"
        )),
        "BC7_UNORM_BLOCK" => Some(include_bytes!("../tests/fixtures/dfd/BC7_UNORM_BLOCK.dfd")),
        "BC7_SRGB_BLOCK" => Some(include_bytes!("../tests/fixtures/dfd/BC7_SRGB_BLOCK.dfd")),
        "ETC2_R8G8B8_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ETC2_R8G8B8_UNORM_BLOCK.dfd"
        )),
        "ETC2_R8G8B8_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ETC2_R8G8B8_SRGB_BLOCK.dfd"
        )),
        "ETC2_R8G8B8A1_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ETC2_R8G8B8A1_UNORM_BLOCK.dfd"
        )),
        "ETC2_R8G8B8A1_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ETC2_R8G8B8A1_SRGB_BLOCK.dfd"
        )),
        "ETC2_R8G8B8A8_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ETC2_R8G8B8A8_UNORM_BLOCK.dfd"
        )),
        "ETC2_R8G8B8A8_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ETC2_R8G8B8A8_SRGB_BLOCK.dfd"
        )),
        "EAC_R11_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/EAC_R11_UNORM_BLOCK.dfd"
        )),
        "EAC_R11_SNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/EAC_R11_SNORM_BLOCK.dfd"
        )),
        "EAC_R11G11_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/EAC_R11G11_UNORM_BLOCK.dfd"
        )),
        "EAC_R11G11_SNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/EAC_R11G11_SNORM_BLOCK.dfd"
        )),
        "ASTC_4x4_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_4x4_UNORM_BLOCK.dfd"
        )),
        "ASTC_4x4_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_4x4_SRGB_BLOCK.dfd"
        )),
        "ASTC_4x4_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_4x4_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_5x4_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_5x4_UNORM_BLOCK.dfd"
        )),
        "ASTC_5x4_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_5x4_SRGB_BLOCK.dfd"
        )),
        "ASTC_5x4_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_5x4_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_5x5_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_5x5_UNORM_BLOCK.dfd"
        )),
        "ASTC_5x5_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_5x5_SRGB_BLOCK.dfd"
        )),
        "ASTC_5x5_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_5x5_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_6x5_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_6x5_UNORM_BLOCK.dfd"
        )),
        "ASTC_6x5_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_6x5_SRGB_BLOCK.dfd"
        )),
        "ASTC_6x5_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_6x5_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_6x6_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_6x6_UNORM_BLOCK.dfd"
        )),
        "ASTC_6x6_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_6x6_SRGB_BLOCK.dfd"
        )),
        "ASTC_6x6_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_6x6_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_8x5_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_8x5_UNORM_BLOCK.dfd"
        )),
        "ASTC_8x5_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_8x5_SRGB_BLOCK.dfd"
        )),
        "ASTC_8x5_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_8x5_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_8x6_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_8x6_UNORM_BLOCK.dfd"
        )),
        "ASTC_8x6_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_8x6_SRGB_BLOCK.dfd"
        )),
        "ASTC_8x6_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_8x6_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_8x8_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_8x8_UNORM_BLOCK.dfd"
        )),
        "ASTC_8x8_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_8x8_SRGB_BLOCK.dfd"
        )),
        "ASTC_8x8_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_8x8_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_10x5_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_10x5_UNORM_BLOCK.dfd"
        )),
        "ASTC_10x5_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_10x5_SRGB_BLOCK.dfd"
        )),
        "ASTC_10x5_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_10x5_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_10x6_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_10x6_UNORM_BLOCK.dfd"
        )),
        "ASTC_10x6_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_10x6_SRGB_BLOCK.dfd"
        )),
        "ASTC_10x6_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_10x6_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_10x8_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_10x8_UNORM_BLOCK.dfd"
        )),
        "ASTC_10x8_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_10x8_SRGB_BLOCK.dfd"
        )),
        "ASTC_10x8_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_10x8_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_10x10_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_10x10_UNORM_BLOCK.dfd"
        )),
        "ASTC_10x10_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_10x10_SRGB_BLOCK.dfd"
        )),
        "ASTC_10x10_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_10x10_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_12x10_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_12x10_UNORM_BLOCK.dfd"
        )),
        "ASTC_12x10_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_12x10_SRGB_BLOCK.dfd"
        )),
        "ASTC_12x10_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_12x10_SFLOAT_BLOCK.dfd"
        )),
        "ASTC_12x12_UNORM_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_12x12_UNORM_BLOCK.dfd"
        )),
        "ASTC_12x12_SRGB_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_12x12_SRGB_BLOCK.dfd"
        )),
        "ASTC_12x12_SFLOAT_BLOCK" => Some(include_bytes!(
            "../tests/fixtures/dfd/ASTC_12x12_SFLOAT_BLOCK.dfd"
        )),
        _ => None,
    }
}
